# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterstedSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='InterstedSubjects',
            new_name='Standard',
        ),
        migrations.AddField(
            model_name='interstedsubject',
            name='std',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Standard'),
        ),
    ]
