# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interstedsubject',
            name='std',
        ),
        migrations.AddField(
            model_name='standard',
            name='sub_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InterstedSubject',
        ),
    ]
