# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20161023_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='sub_name',
            field=models.CharField(max_length=100),
        ),
    ]
